# HW_L03_02_pandas_matplotlib

This exercise consists of two parts:

1. **Data preprocessing and preparation using Pandas**  
2. **Data visualization using Seaborn and Matplotlib**

The first part involves data cleaning, preprocessing, and general data preparation tasks performed with Pandas.  
The second part focuses on plotting and creating visualizations required for presenting and analyzing the data.

In [5]:
# basic
import os

# Analysis
import numpy as np
import pandas as pd

# plot
import matplotlib.pyplot as plt
import seaborn as sns

## 1. Data Preparation and Processing with **Pandas**
 
Mastering dataset merging, working with time series, and creating pivot tables.

### Task 1 : Data Files   

- **orders.csv**: Transaction history, including sales amount (Sales) and profit (Profit).  
- **products.csv**: Details of the sold products (such as category and product name).  
- **customers.csv**: Customer demographic information (such as region and customer type).

In [60]:
# first way
PATH = os.getcwd()
PATH_CUSTOMERS = PATH + "\\customers.csv"
PATH_ORDERS = PATH + "\\orders.csv"
PATH_PRODUCTS = PATH + "\\products.csv"

customers = pd.read_csv(PATH_CUSTOMERS)
orders = pd.read_csv(PATH_ORDERS)
products = pd.read_csv(PATH_PRODUCTS)

#### Second way   
This method helps when you have **many files** and want to load **all of them at once**,  
creating separate DataFrames with **their own names**.

Important note:  
DataFrame names **must not** contain characters like `-`, `.`, spaces, or other invalid symbols.  
Therefore, the file names must be **cleaned first** to produce valid Python variable names.

1. We identify the main directory we are currently in
    
    ```python
    PATH = os.getcwd()
    ```
    This step fixes the read error.  
    If you are using a `cookiecutter project`, the data files are usually located inside the **raw** folder, not in the working directory.  
    Therefore, you cannot read the files directly without specifying their full path.

---

2. We store the names of the files inside the target folder in a list.  
   By applying a condition on the file format, we ensure that only the desired files are included in the list, while other file types are excluded.   
   ```python
   NAME_FILE = [file for file in os.listdir() if file.endswith(".csv")]
   ```

---

3. To organize the information and keep a DataFrame of the files, we convert the list from step 2 into a DataFrame. 

    ```python
    file_info_csv = pd.DataFrame(NAME_FILE, columns=['file_name'])
    ```
   We then add a new column that extracts the DataFrame names from the corresponding file names.
   ```python
   file_info_csv["dataframe_name"] = file_info_csv['file_name'].str.replace(".csv", "")
   ```

---

4. Using a `for` loop and the `globals()` function, we read each file and assign the resulting DataFrame to a variable that matches its own name.
    ```python
    for i in range(len(file_info_csv.index)):
    # make path
    PATH_READ_DATA = PATH + "\\" + file_info_csv["file_name"].iloc[i]
    # read and make df by name with globals()
    globals()[file_info_csv["dataframe_name"].iloc[i]] = pd.read_csv(PATH_READ_DATA)
    ```
    * The `file_name` column contains the file names **including** the `.csv` extension, while the `dataframe_name` column contains the cleaned names that DataFrames should be created with, where the `.csv` string has been removed.
    * The `globals()` function tells Python that the value obtained from the DataFrame is **not a string**, but should be treated as a **variable name**.

In [ ]:
# second way
# I use this way always

PATH = os.getcwd()
NAME_FILE = [file for file in os.listdir() if file.endswith(".csv")]

file_info_csv = pd.DataFrame(NAME_FILE, columns=['file_name'])

file_info_csv["dataframe_name"] = file_info_csv['file_name'].str.replace(".csv", "")

for i in range(len(file_info_csv.index)):
    # make path
    PATH_READ_DATA = PATH + "\\" + file_info_csv["file_name"].iloc[i]
    # read and make df by name with globals()
    globals()[file_info_csv["dataframe_name"].iloc[i]] = pd.read_csv(PATH_READ_DATA)

In [73]:
file_info_csv

       file_name dataframe_name
0  customers.csv      customers
1     orders.csv         orders
2   products.csv       products

In [66]:
globals()[file_info_csv["dataframe_name"][0]].head()

  CustomerID   CustomerName      Segment   Region         State          City
0   DP-13000  Darren Powers     Consumer  Central         Texas       Houston
1   PO-19195  Phillina Ober  Home Office  Central      Illinois    Naperville
2   MB-18085     Mick Brown     Consumer     East  Pennsylvania  Philadelphia
3   ME-17320  Maria Etezadi  Home Office    South      Kentucky     Henderson
4   JO-15145  Jack O'Briant    Corporate    South       Georgia        Athens

In [67]:
customers.head()

  CustomerID   CustomerName      Segment   Region         State          City
0   DP-13000  Darren Powers     Consumer  Central         Texas       Houston
1   PO-19195  Phillina Ober  Home Office  Central      Illinois    Naperville
2   MB-18085     Mick Brown     Consumer     East  Pennsylvania  Philadelphia
3   ME-17320  Maria Etezadi  Home Office    South      Kentucky     Henderson
4   JO-15145  Jack O'Briant    Corporate    South       Georgia        Athens

#### customers information

In [75]:
customers.head()

  CustomerID   CustomerName      Segment   Region         State          City
0   DP-13000  Darren Powers     Consumer  Central         Texas       Houston
1   PO-19195  Phillina Ober  Home Office  Central      Illinois    Naperville
2   MB-18085     Mick Brown     Consumer     East  Pennsylvania  Philadelphia
3   ME-17320  Maria Etezadi  Home Office    South      Kentucky     Henderson
4   JO-15145  Jack O'Briant    Corporate    South       Georgia        Athens

In [ ]:
print(f"shape of customers dataframe: {customers.shape}")
print(f"Count null value of customers dataframe: \n{customers.isnull().sum()}")

shape of customers dataframe: (793, 6)
Count null value of customers dataframe:
CustomerID      0
CustomerName    0
Segment         0
Region          0
State           0
City            0
dtype: int64

In [77]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 793 entries, 0 to 792
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    793 non-null    str
 1   CustomerName  793 non-null    str
 2   Segment       793 non-null    str
 3   Region        793 non-null    str
 4   State         793 non-null    str
 5   City          793 non-null    str
dtypes: str(6)
memory usage: 37.3 KB

In [81]:
customers.describe()

       CustomerID   CustomerName   Segment Region       State         City
count         793            793       793    793         793          793
unique        793            793         3      4          43          247
top      DP-13000  Darren Powers  Consumer   West  California  Los Angeles
freq            1              1       409    252         156           59

#### orders information

In [83]:
orders.head()

,OrderID,OrderDate,CustomerID,ProductID,Sales,Quantity,Discount,Profit
0,CA-2019-103800,2019-01-03,DP-13000,OFF-PA-10000174,16.448,2,0.2,5.5512
1,CA-2019-112326,2019-01-04,PO-19195,OFF-LA-10003223,11.784,3,0.2,4.2717
2,CA-2019-112326,2019-01-04,PO-19195,OFF-ST-10002743,272.736,3,0.2,-64.7748
3,CA-2019-112326,2019-01-04,PO-19195,OFF-BI-10004094,3.540,2,0.8,-5.4870
4,CA-2019-141817,2019-01-05,MB-18085,OFF-AR-10003478,19.536,3,0.2,4.8840

In [84]:
print(f"shape of customers dataframe: {orders.shape}")
print(f"Count null value of customers dataframe: \n{orders.isnull().sum()}")

shape of customers dataframe: (9994, 8)
Count null value of customers dataframe:
OrderID       0
OrderDate     0
CustomerID    0
ProductID     0
Sales         0
Quantity      0
Discount      0
Profit        0
dtype: int64

In [86]:
orders.describe()

              Sales     Quantity     Discount       Profit
count   9994.000000  9994.000000  9994.000000  9994.000000
mean     229.858001     3.789574     0.156203    28.656896
std      623.245101     2.225110     0.206452   234.260108
min        0.444000     1.000000     0.000000 -6599.978000
25%       17.280000     2.000000     0.000000     1.728750
50%       54.490000     3.000000     0.200000     8.666500
75%      209.940000     5.000000     0.200000    29.364000
max    22638.480000    14.000000     0.800000  8399.976000

#### products inormation

In [87]:
products.head()

,ProductID,Category,SubCategory,ProductName
0,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form..."
1,OFF-LA-10003223,Office Supplies,Labels,Avery 508
2,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving
3,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs
4,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...

In [88]:
print(f"shape of customers dataframe: {orders.shape}")
print(f"Count null value of customers dataframe: \n{orders.isnull().sum()}")

shape of customers dataframe: (9994, 8)
Count null value of customers dataframe:
OrderID       0
OrderDate     0
CustomerID    0
ProductID     0
Sales         0
Quantity      0
Discount      0
Profit        0
dtype: int64

In [89]:
products.describe()

              ProductID         Category SubCategory ProductName
count              1862             1862        1862        1862
unique             1862                3          17        1818
top     OFF-PA-10000174  Office Supplies       Paper     Staples
freq                  1             1083         276          10

### Task 2 Merge Instructions (Translated for Jupyter Notebook)

The `orders` table contains only ID fields and no detailed information.  
We must add the related information to it.

**Step 1:**  
Merge the `orders` DataFrame with the `products` DataFrame based on the `ProductID` column.

**Step 2:**  
Merge the result with the `customers` DataFrame based on the `CustomerID` column.

**Step 3:**  
Store the final merged result in a variable named `df_master`.  
Then check its shape to ensure no data was lost.

In [128]:
# first way
df_master = (orders.merge(products,
                          left_on="ProductID",
                          right_on="ProductID",
                          how="left").merge(customers,
                                            left_on="CustomerID",
                                            right_on="CustomerID",
                                            how="left"))

In [129]:
df_master.head(3)

,OrderID,OrderDate,CustomerID,ProductID,Sales,Quantity,Discount,Profit,Category,SubCategory,ProductName,CustomerName,Segment,Region,State,City
0,CA-2019-103800,2019-01-03,DP-13000,OFF-PA-10000174,16.448,2,0.2,5.5512,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",Darren Powers,Consumer,Central,Texas,Houston
1,CA-2019-112326,2019-01-04,PO-19195,OFF-LA-10003223,11.784,3,0.2,4.2717,Office Supplies,Labels,Avery 508,Phillina Ober,Home Office,Central,Illinois,Naperville
2,CA-2019-112326,2019-01-04,PO-19195,OFF-ST-10002743,272.736,3,0.2,-64.7748,Office Supplies,Storage,SAFCO Boltless Steel Shelving,Phillina Ober,Home Office,Central,Illinois,Naperville

In [134]:
orders.shape, df_master.shape

# orders   = 8 columns
# products = 4 columns
# customers= 6 columns
# df_master = 8 + 4 + 6 -(2) = 16

((9994, 8), (9994, 16))

In [136]:
orders.shape[0] == df_master.shape[0]

True

In [137]:
# second way
merge_orders_products = pd.merge(orders,
                                 products,
                                 left_on="ProductID",
                                 right_on= "ProductID",
                                 how="left")

df_master = pd.merge(merge_orders_products,
                     customers,
                     left_on="CustomerID",
                     right_on="CustomerID",
                     how="left")
df_master.head(2)

,OrderID,OrderDate,CustomerID,ProductID,Sales,Quantity,Discount,Profit,Category,SubCategory,ProductName,CustomerName,Segment,Region,State,City
0,CA-2019-103800,2019-01-03,DP-13000,OFF-PA-10000174,16.448,2,0.2,5.5512,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",Darren Powers,Consumer,Central,Texas,Houston
1,CA-2019-112326,2019-01-04,PO-19195,OFF-LA-10003223,11.784,3,0.2,4.2717,Office Supplies,Labels,Avery 508,Phillina Ober,Home Office,Central,Illinois,Naperville

In [138]:
orders.shape, df_master.shape

((9994, 8), (9994, 16))

In [139]:
orders.shape[0] == df_master.shape[0]

True