# HW_L03_01_numpy_pandas

This project is divided into **six sections**:

1. **Data Structure Fundamentals – NumPy Basics**
2. **Numerical Operations and Data Preprocessing**  
3. **Data Filtering and Feature Engineering**  
4. **Exploratory Data Analysis (EDA) on an ML Class Dataset**  
5. **Data Cleaning and Preprocessing**  
6. **Feature Engineering and Group Analysis**

In [1]:
import os
import numpy as np
import pandas as pd

### 1. **Data Structure Fundamentals – NumPy Basics**

Task 1   
Create a **one-dimensional NumPy array** that contains **12 consecutive integers greater than 5**.

In [2]:
# by numpy arange
NUMBER = 5
feature_vector = np.arange(NUMBER, NUMBER + 12)
feature_vector

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [3]:
# by list and numpy array
NUMBER = 5
feature_vector = np.array([i + NUMBER for i in range(12)])
feature_vector

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

Task 2   
Create a **2D NumPy array** with shape **3×4** filled with **pseudo‑random integers between 0 and 9**.  
Use:
```python
np.random.seed(42)

In [4]:
np.random.seed(42)
feature_matrix = np.random.randint(0, 10, size=(3, 4))
feature_matrix

array([[6, 3, 7, 4],
       [6, 9, 2, 6],
       [7, 4, 3, 7]], dtype=int32)

In [5]:
print(f"feature_vector size: {feature_vector.size}, feature_matrix size: {feature_matrix.size}")
print(f"feature_vector ndim: {feature_vector.ndim}, feature_matrix ndim: {feature_matrix.ndim}")
print(f"feature_vector shape: {feature_vector.shape}, feature_matrix shape: {feature_matrix.shape}")
print(f"feature_vector dtype: {feature_vector.dtype}, feature_matrix dtype: {feature_matrix.dtype}")

feature_vector size: 12, feature_matrix size: 12
feature_vector ndim: 1, feature_matrix ndim: 2
feature_vector shape: (12,), feature_matrix shape: (3, 4)
feature_vector dtype: int64, feature_matrix dtype: int32

In [6]:
# by dataframe and table
info_feature_vector = [feature_vector.size, feature_vector.ndim, feature_vector.shape, feature_vector.dtype]
info_feature_matrix = [feature_matrix.size, feature_matrix.ndim, feature_matrix.shape, feature_matrix.dtype]

pd.DataFrame([info_feature_vector, info_feature_matrix],
             columns=["size", "ndim", "shape", "dtype"],
             index = ["feature_vector", "feature_matrix"])

                size  ndim   shape  dtype
feature_vector    12     1   (12,)  int64
feature_matrix    12     2  (3, 4)  int32

Task 3    
Indexing and Slicing – Accessing Data

Perform the following operations on `feature_matrix`:

- Print the element at **row 2, column 3**.
- Print the **entire first row** of `feature_matrix`.
- Print the **entire last column** of `feature_matrix`.
- Select a **2×2 submatrix from the top-right corner** of `feature_matrix`.

In [7]:
feature_matrix

array([[6, 3, 7, 4],
       [6, 9, 2, 6],
       [7, 4, 3, 7]], dtype=int32)

In [8]:
# value 2,3 = [2-1, 3-1]
print(f"row 2 and column 3 is {feature_matrix[1, 2]}")
print("---------------------------")
# row 1 = [0, :]
print(f"row 1 is {feature_matrix[0, :]}")
print("---------------------------")
# column end = [:, -1]
print(f"column end is {feature_matrix[:, -1]}")
print("---------------------------")
# Matrix 2x2 = [:2, :2] or [0:2, 0:2]
print(f"Matrix 2x2 is\n {feature_matrix[:2, :2]}") # \n print to next line

row 2 and column 3 is 2
---------------------------
row 1 is [6 3 7 4]
---------------------------
column end is [4 6 7]
---------------------------
Matrix 2x2 is
 [[6 3]
 [6 9]]

Task 4   
Reshaping Data  

* Reshape `feature_vector` into a **2D array with 4 rows and 3 columns**.

* Convert `feature_matrix` into a **1D array (flatten it)**.

In [9]:
feature_vector

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [10]:
# feature_vector is 1d -> reshape(4,3)
feature_vector.reshape(4,3)

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16]])

In [11]:
feature_matrix

array([[6, 3, 7, 4],
       [6, 9, 2, 6],
       [7, 4, 3, 7]], dtype=int32)

In [12]:
# fisrt way -> 1d and flatten
# shape is (1, feature_vector.size)
feature_vector.reshape(1, feature_vector.size)[0]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [13]:
# second way -> 1d and flatten
feature_vector.flatten()

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

Task 5   

Combining Datasets

- Create a new **3×4 matrix** filled with ones.
- Vertically stack this matrix with your original `feature_matrix`.
- Create a **3×1 column vector** with values `[10, 20, 30]`.
- Horizontally stack this column vector to your `feature_matrix`.

In [14]:
# Create one matrix 3x4 by 1
New_Matrix_Ones = np.ones((3,4), dtype="int")
New_Matrix_Ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [15]:
# first way
# concat New_Matrix_Ones and feature_matrix by axis = 0 (vertically)
np.concatenate([New_Matrix_Ones, feature_matrix], axis= 0)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [6, 3, 7, 4],
       [6, 9, 2, 6],
       [7, 4, 3, 7]])

In [16]:
# second way
np.vstack([New_Matrix_Ones, feature_matrix])

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [6, 3, 7, 4],
       [6, 9, 2, 6],
       [7, 4, 3, 7]])

In [17]:
# Create one array 3x1
new_array = np.array([10, 20, 30]).reshape(3,1)
new_array

array([[10],
       [20],
       [30]])

In [18]:
# first way
# concat new_array and feature_matrix by axis = 1 (horizontally)
np.concatenate([new_array, feature_matrix], axis= 1)

array([[10,  6,  3,  7,  4],
       [20,  6,  9,  2,  6],
       [30,  7,  4,  3,  7]])

In [19]:
# second way
np.hstack([new_array, feature_matrix])

array([[10,  6,  3,  7,  4],
       [20,  6,  9,  2,  6],
       [30,  7,  4,  3,  7]])

### 2. **Numerical Operations and Data Preprocessing**  
This exercise introduces the power of **vectorized operations, aggregate functions, and broadcasting**.  
These are fundamental concepts for data preprocessing and machine learning, such as **normalization**.

Task 1   
Create a **2D NumPy array** named `scores` with shape **(15, 3)** containing **pseudo‑random integers between 50 and 100**.  
Use:

`np.random.seed(100)`

- Compute the **mean score of each test** (mean of each column).
- Compute the **standard deviation of the test scores**.
- Find the **highest score obtained in the third test**.
- Compute the **average score of each student** (mean of each row).

In [20]:
np.random.seed(100)
scores = np.random.randint(50, 101, size=(15, 3)) # [50, 101)
scores

array([[58, 74, 53],
       [89, 73, 65],
       [98, 60, 80],
       [84, 52, 84],
       [64, 84, 99],
       [98, 74, 65],
       [86, 93, 66],
       [59, 79, 72],
       [52, 77, 94],
       [54, 81, 51],
       [63, 69, 86],
       [54, 77, 53],
       [57, 99, 97],
       [51, 64, 57],
       [66, 52, 91]], dtype=int32)

In [21]:
# Compute the mean score of each test (mean of each column)
# first way
print(f"avrage scores each test 1 : {scores[:, 0].mean():.4f}") # print folat by format .4f
print(f"avrage scores each test 2 : {scores[:, 1].mean():.4f}")
print(f"avrage scores each test 3 : {scores[:, 2].mean():.4f}")

avrage scores each test 1 : 68.8667
avrage scores each test 2 : 73.8667
avrage scores each test 3 : 74.2000

In [22]:
type(scores.shape)

tuple

In [23]:
# Second way
print(f"type of scores.shape is {type(scores.shape)}") #is one tupel by 2 value
NUMBER_TEST = scores.shape[1] # need second value
for test in range(NUMBER_TEST):
    print(f"avrage scores each test {test + 1} : {scores[:, test].mean():.4f}")

type of scores.shape is <class 'tuple'>
avrage scores each test 1 : 68.8667
avrage scores each test 2 : 73.8667
avrage scores each test 3 : 74.2000

In [24]:
# Compute the standard deviation of the test scores
# first way
print(f"std scores each test 1 : {scores[:, 0].std():.4f}") # print folat by format .4f
print(f"std scores each test 2 : {scores[:, 1].std():.4f}")
print(f"std scores each test 3 : {scores[:, 2].std():.4f}")

std scores each test 1 : 16.5202
std scores each test 2 : 12.8264
std scores each test 3 : 16.4365

In [25]:
# Second way
print(f"type of scores.shape is {type(scores.shape)}") #is one tupel by 2 value
NUMBER_TEST = scores.shape[1] # need second value
for test in range(NUMBER_TEST):
    print(f"std scores each test {test + 1} : {scores[:, test].std():.4f}")

type of scores.shape is <class 'tuple'>
std scores each test 1 : 16.5202
std scores each test 2 : 12.8264
std scores each test 3 : 16.4365

In [26]:
# Find the highest score obtained in the third test
# first way
print(f"Max scores 3rd test: {scores[:, 2].max()}")
# second way
print(f"Max scores 3rd test: {scores[:, -1].max()}")

Max scores 3rd test: 99
Max scores 3rd test: 99

In [27]:
# Compute the average score of each student(mean of each row)
# first way
print(f"avrage scores each student: \n{scores.mean(axis=1)}")

avrage scores each student:
[61.66666667 75.66666667 79.33333333 73.33333333 82.33333333 79.
 81.66666667 70.         74.33333333 62.         72.66666667 61.33333333
 84.33333333 57.33333333 69.66666667]

In [28]:
# first way
TOTAL_ROW = scores.shape[0] # total row = scores.shape[0]
avrage_student_score = scores.mean(axis=1).reshape(TOTAL_ROW, 1)
print(f"avrage scores each student: \n{avrage_student_score}")

avrage scores each student:
[[61.66666667]
 [75.66666667]
 [79.33333333]
 [73.33333333]
 [82.33333333]
 [79.        ]
 [81.66666667]
 [70.        ]
 [74.33333333]
 [62.        ]
 [72.66666667]
 [61.33333333]
 [84.33333333]
 [57.33333333]
 [69.66666667]]

Task 2   
Broadcasting

Assume the instructor decides to improve all students' scores in the **first test** by adding **5 points**.

Create a new array called `curved_scores` in which **only the first column** of the `scores` array has increased by **5**.

Use **broadcasting** to do this.

In [29]:
print(f"main score test 1 \n{scores[:,0]}")
print("---------------------first way----------------------")
# first way
curved_scores = np.array(scores[:,0] + 5)
print(f"test number 1 add 5 score to esch score \n{curved_scores}")
print("---------------------second way--------------------")
# second way
curved_scores = np.add(scores[:, 0], 5)
print(f"test number 1 add 5 score to esch score \n{curved_scores}")

main score test 1
[58 89 98 84 64 98 86 59 52 54 63 54 57 51 66]
---------------------first way----------------------
test number 1 add 5 score to esch score
[ 63  94 103  89  69 103  91  64  57  59  68  59  62  56  71]
---------------------second way--------------------
test number 1 add 5 score to esch score
[ 63  94 103  89  69 103  91  64  57  59  68  59  62  56  71]

In [30]:
print("time run each way")
%timeit np.array(scores[:,0] + 5)
%timeit np.add(scores[:, 0], 5)

time run each way
16 μs ± 1.14 μs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
10.3 μs ± 75.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

Task 3    
Data Normalization

A very common step in ML data preprocessing is **feature normalization**. This is achieved by subtracting the mean and dividing by the standard deviation for each feature.

- Calculate the **mean** and **standard deviation** of each test from the original `scores` array.
- Create a new array named `normalized_scores` using the **Z-score** formula:
  
  $$(scores - mean) / std$$

  You must correctly apply **broadcasting** to subtract the 1D `mean` and `std` arrays from the 2D `scores` matrix and then divide.
- To verify your results, calculate the mean and standard deviation for each column of `normalized_scores`. The mean should be very close to **0**, and the standard deviation should be very close to **1**.

In [31]:
# Calculate the mean and std of each test

NUMBER_COLUMN = scores.shape[1]

for test in range(NUMBER_COLUMN):
    print(f"test number {test +1}: mean: {scores[:,test].mean():.4f} -- std: {scores[:,test].std():.4f}")

test number 1: mean: 68.8667 -- std: 16.5202
test number 2: mean: 73.8667 -- std: 12.8264
test number 3: mean: 74.2000 -- std: 16.4365

In [32]:
# Create a new array named normalized_scores using the Z-score
# first way
normalized_scores = (scores - (scores.mean(axis=0))) / (scores.std(axis=0))
print(normalized_scores)

[[-0.65778233  0.01039526 -1.2898088 ]
 [ 1.21871327 -0.06756917 -0.55972835]
 [ 1.76350231 -1.08110678  0.35287222]
 [ 0.91605269 -1.70482223  0.59623237]
 [-0.29458963  0.79003957  1.50883294]
 [ 1.76350231  0.01039526 -0.55972835]
 [ 1.03711692  1.49171945 -0.49888831]
 [-0.59725021  0.40021741 -0.13384808]
 [-1.02097502  0.24428855  1.20463275]
 [-0.89991079  0.55614628 -1.41148888]
 [-0.35512175 -0.3794269   0.71791245]
 [-0.89991079  0.24428855 -1.2898088 ]
 [-0.71831444  1.95950604  1.38715286]
 [-1.08150714 -0.76924906 -1.04644865]
 [-0.1735254  -1.70482223  1.02211264]]

In [33]:
# second way
STD_COLUMN = scores.std(axis=0) # in column
STD_MEAN = scores.mean(axis=0) # in column
normalized_scores = (scores - STD_MEAN) / STD_COLUMN
normalized_scores

array([[-0.65778233,  0.01039526, -1.2898088 ],
       [ 1.21871327, -0.06756917, -0.55972835],
       [ 1.76350231, -1.08110678,  0.35287222],
       [ 0.91605269, -1.70482223,  0.59623237],
       [-0.29458963,  0.79003957,  1.50883294],
       [ 1.76350231,  0.01039526, -0.55972835],
       [ 1.03711692,  1.49171945, -0.49888831],
       [-0.59725021,  0.40021741, -0.13384808],
       [-1.02097502,  0.24428855,  1.20463275],
       [-0.89991079,  0.55614628, -1.41148888],
       [-0.35512175, -0.3794269 ,  0.71791245],
       [-0.89991079,  0.24428855, -1.2898088 ],
       [-0.71831444,  1.95950604,  1.38715286],
       [-1.08150714, -0.76924906, -1.04644865],
       [-0.1735254 , -1.70482223,  1.02211264]])

In [34]:
# Third way
STD_COLUMN = scores.std(axis=0) # in column
STD_MEAN = scores.mean(axis=0) # in column
normalized_scores = np.divide(np.subtract(scores, STD_MEAN), STD_COLUMN)
normalized_scores

array([[-0.65778233,  0.01039526, -1.2898088 ],
       [ 1.21871327, -0.06756917, -0.55972835],
       [ 1.76350231, -1.08110678,  0.35287222],
       [ 0.91605269, -1.70482223,  0.59623237],
       [-0.29458963,  0.79003957,  1.50883294],
       [ 1.76350231,  0.01039526, -0.55972835],
       [ 1.03711692,  1.49171945, -0.49888831],
       [-0.59725021,  0.40021741, -0.13384808],
       [-1.02097502,  0.24428855,  1.20463275],
       [-0.89991079,  0.55614628, -1.41148888],
       [-0.35512175, -0.3794269 ,  0.71791245],
       [-0.89991079,  0.24428855, -1.2898088 ],
       [-0.71831444,  1.95950604,  1.38715286],
       [-1.08150714, -0.76924906, -1.04644865],
       [-0.1735254 , -1.70482223,  1.02211264]])

In [35]:
# test part 2 if std is 1 and mean is 0
NUMER_COLUMN_NORMALIZED = normalized_scores.shape[1]
print("std and mean nomalized score each test is by format .10f:")
for i in range(NUMER_COLUMN_NORMALIZED):
    print(f"Normalized score test number {i +1}: mean: {normalized_scores[:,i].mean():.10f} -- std: {normalized_scores[:,i].std():.10f}")

std and mean nomalized score each test is by format .10f:
Normalized score test number 1: mean: 0.0000000000 -- std: 1.0000000000
Normalized score test number 2: mean: 0.0000000000 -- std: 1.0000000000
Normalized score test number 3: mean: -0.0000000000 -- std: 1.0000000000

### 3. Data Filtering and Feature Engineering

**Objective:** This exercise focuses on using **Boolean masking** to filter data and create new features.

In this exercise, we will continue to use the same `scores` dataset from the previous exercise.

Task 1   
Identifying Top Students

- Create a **Boolean mask** that identifies all scores in the `scores` array that are **greater than 95**.
- Using this mask, **count the number of scores above 95**.
- Create a new array called `high_performers_scores` that contains **only the scores**

In [36]:
scores

array([[58, 74, 53],
       [89, 73, 65],
       [98, 60, 80],
       [84, 52, 84],
       [64, 84, 99],
       [98, 74, 65],
       [86, 93, 66],
       [59, 79, 72],
       [52, 77, 94],
       [54, 81, 51],
       [63, 69, 86],
       [54, 77, 53],
       [57, 99, 97],
       [51, 64, 57],
       [66, 52, 91]], dtype=int32)

In [46]:
# Create a Boolean mask that identifies all scores in the scores array that are greater than 95

# MASK_SCORE_GREATER_95 = scores > 95
MASK_SCORE_GREATER_95 = np.greater(scores, 95)
MASK_SCORE_GREATER_95

array([[False, False, False],
       [False, False, False],
       [ True, False, False],
       [False, False, False],
       [False, False,  True],
       [ True, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False,  True,  True],
       [False, False, False],
       [False, False, False]])

In [47]:
# Using this mask, count the number of scores above 95
print(f"total scores greater than 95 is {MASK_SCORE_GREATER_95.sum()}")

total scores greater than 95 is 5

In [63]:
# Create a new array called high_performers_scores that contains only the scores
high_performers_scores = scores[MASK_SCORE_GREATER_95]
print(f"Scores greater than 95 is: {high_performers_scores}")

Scores greater than 95 is: [98 99 98 99 97]

Task 2    
Conditional Analysis

Compute the **average score of the second test**, but **only** for students whose **first test score is less than or equal to 70**.

In [74]:
# first way
MASK_TEST1_LESS_EQUAL_70 = scores[:,0] <= 70
# test 2 is [:,1]
scores[MASK_TEST1_LESS_EQUAL_70][:,1].mean()

np.float64(75.6)

In [75]:
# second way
MASK_TEST1_LESS_EQUAL_70 = np.less_equal(scores[:,0], 70)
scores[MASK_TEST1_LESS_EQUAL_70][:,1].mean()

np.float64(75.6)

Task 3   
Feature Engineering – Creating a Pass/Fail Feature

Create a new **1D array** called `pass_fail`.  
A student is considered **pass** (`True`) if their **average score across all three tests** is **greater than 65**.  
Otherwise, the student is considered **fail** (`False`).

In [83]:
# first Way
pass_fail = scores.mean(axis=1) > 65
print(f"Array of student with pass or fail: \n{pass_fail}")
print("--------------------------------------")
#second way
pass_fail = np.greater(scores.mean(axis=1), 65)
print(f"Array of student with pass or fail: \n{pass_fail}")

Array of student with pass or fail:
[False  True  True  True  True  True  True  True  True False  True False
  True False  True]
--------------------------------------
Array of student with pass or fail:
[False  True  True  True  True  True  True  True  True False  True False
  True False  True]

Task 4   
Student Filtering – Excellent Students

- Identify students who scored **more than 90** in **each test**.
- Create a **binary mask** for these students.
- Use this mask to **select and print the scores** of these students, based on this **mask**.

In [87]:
scores

array([[58, 74, 53],
       [89, 73, 65],
       [98, 60, 80],
       [84, 52, 84],
       [64, 84, 99],
       [98, 74, 65],
       [86, 93, 66],
       [59, 79, 72],
       [52, 77, 94],
       [54, 81, 51],
       [63, 69, 86],
       [54, 77, 53],
       [57, 99, 97],
       [51, 64, 57],
       [66, 52, 91]], dtype=int32)

In [99]:
# first way
MASK_EXCELLENT_STUDENT = ((scores[:,0]>90) & (scores[:,1]>90) & (scores[:,2]>90))
Excellent_Student = scores[MASK_EXCELLENT_STUDENT]
if Excellent_Student.size == 0:
    print("cannot found excellent student")
else:
    print(f"Excellent student is ")

print("-------------------------------------")
# second way
MASK_EXCELLENT_STUDENT = (scores > 90).all(axis=1)
Excellent_Student = scores[MASK_EXCELLENT_STUDENT]
if Excellent_Student.size == 0:
    print("cannot found excellent student")
else:
    print(f"Excellent student is ")

cannot found excellent student
-------------------------------------
cannot found excellent student

### 4. Exploratory Data Analysis (EDA) on a Classic ML Dataset

**Objective:** 
This project aims to familiarize you with machine learning by exploring and analyzing a dataset.

**Dataset Information:**  
The Titanic dataset is available at the following URL:  
[https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv](https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv)


Task 1   
**Loading the Dataset:**  
1. Load the Titanic dataset into a **DataFrame** named `df` using the following command:

   `df = pd.read_csv("URL")`

2. Print 5 first row   

   `df.head()`

In [2]:
PATH = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(PATH)

In [ ]:
# Due to internet connectivity issues, we will save the file in .csv format
PATH_SAVE = os.getcwd() + "\\titanic.csv"
df.to_csv(PATH_SAVE)

In [3]:
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Task 2   
Initial Inspection

- Use the `info()` method. This is a vital first step to understand the **data types of columns** and identify **missing values**.

- Use the `describe()` method to obtain **descriptive statistics** (mean, standard deviation, etc.) for **numeric columns**.

In [309]:
df.info()
# age has nan, Cabin has nan, Embarked has nan

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [310]:
df.describe() # describe return number columns

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

Task 3   
Data Selection

- In machine learning, we work with **features (inputs)** and **targets (predictable outputs)**.

- Select and display the `Survived` column. This is a **Pandas Series**. Print its data type.

- Select and display the columns `Age`, `Pclass`, and `Sex`.

- Using `loc`, display the data of the passenger with **index 3**.

- Using `iloc`, display the data of **index 5** and **index 3**.

In [4]:
# Select and display the Survived column. This is a Pandas Series. Print its data type.
# first way
print(f"type Survived is {df["Survived"].dtype}") # print(value type)
print("---------------------------------------")
# second way
print(f"type Survived by numpy is {np.dtype(df["Survived"])}") # print(value type)
print("---------------------------------------")
# Terid way
print(f"type Survived by python is {type(df["Survived"])}") # print(column type)

type Survived is int64
---------------------------------------
type Survived by numpy is int64
---------------------------------------
type Survived by python is <class 'pandas.Series'>

In [148]:
%timeit df["Survived"].dtype
%timeit np.dtype(df["Survived"])
%timeit type(df["Survived"])

99.5 μs ± 29.7 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
117 μs ± 2.08 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
76.5 μs ± 1.87 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [312]:
# Select and display the columns Age, Pclass, and Sex
df[["Age", "Pclass", "Sex"]] # mask by one list of columns

      Age  Pclass     Sex
0    22.0       3    male
1    38.0       1  female
2    26.0       3  female
3    35.0       1  female
4    35.0       3    male
..    ...     ...     ...
886  27.0       2    male
887  19.0       1  female
888   NaN       3  female
889  26.0       1    male
890  32.0       3    male

[891 rows x 3 columns]

In [313]:
# Using loc, display the data of the passenger with index 3
df.loc[3]

PassengerId                                               4
Survived                                                  1
Pclass                                                    1
Name           Futrelle, Mrs. Jacques Heath (Lily May Peel)
Sex                                                  female
Age                                                    35.0
SibSp                                                     1
Parch                                                     0
Ticket                                               113803
Fare                                                   53.1
Cabin                                                  C123
Embarked                                                  S
Name: 3, dtype: object

In [314]:
# Using iloc, display the data of index 5 and index 3
df.iloc[[5, 3]] # mask by one list [5, 3]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

Task 4    
Data Filtering

Using **boolean masking**, answer the following questions:

- How many passengers survived?  
  *(Hint: you can apply `.sum()` to a Boolean Series.)*

- Create a new **DataFrame** named `survivors` that contains **only the data of survived passengers**.

- Among the survivors, how many were **male**?

- Create a **DataFrame** that includes only **first-class passengers** (`Pclass == 1`) who are **older than 50 years**.

In [315]:
# How many passengers survived?
print(f"name of all colums is \n{df.columns}")
print(f"Value of Survived columns is :{df["Survived"].unique()}")
print("---------------------------------")
print(f"Number of parsons survived is {df["Survived"].sum()}") # sum total 1 in this column

name of all colums is
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')
Value of Survived columns is :[0 1]
---------------------------------
Number of parsons survived is 342

In [5]:
# Create a new DataFrame named survivors that contains only the data of survived passengers


# MASK_SURVIORS = df["Survived"] == 1 #python form
MASK_SURVIORS = df["Survived"].eq(1) # pandas form
survivors = df[MASK_SURVIORS]
survivors

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [6]:
# Among the survivors, how many were male?
print(f"Value of Sex columns is : {survivors["Sex"].unique()}")

MASK_SURVIORS_MALE = survivors["Sex"].eq("male")
print("-----------------------------")
# first way
print(f"Total Male survivors is {survivors[MASK_SURVIORS_MALE].shape[0]}") # shape is a Tupel (row, column)
print("-----------------------------")
#second way
print(f"Total Male survivors is {survivors[MASK_SURVIORS_MALE]["Survived"].sum()}")
print("-----------------------------")
#Third way
print(f"Total Male survivors is {len(survivors[MASK_SURVIORS_MALE])}")
print("-----------------------------")
# Fourth way
print(f"Total Male survivors is {survivors[MASK_SURVIORS_MALE]["Survived"].count()}") # all Survived are 1

Value of Sex columns is : <StringArray>
['female', 'male']
Length: 2, dtype: str
-----------------------------
Total Male survivors is 109
-----------------------------
Total Male survivors is 109
-----------------------------
Total Male survivors is 109
-----------------------------
Total Male survivors is 109

In [7]:
# Create a DataFrame that includes only first-class passengers
# (Pclass == 1) who are older than 50 years

MASK_PLCASS_AGE = ((df["Pclass"].eq(1)) & (df["Age"].gt(50))) # (eq: == ) (gt: >)
df_pcalss_age = df[MASK_PLCASS_AGE]
df_pcalss_age.describe()[["Pclass", "Age"]]

       Pclass        Age
count    39.0  39.000000
mean      1.0  58.974359
std       0.0   6.502984
min       1.0  51.000000
25%       1.0  54.000000
50%       1.0  58.000000
75%       1.0  62.000000
max       1.0  80.000000

### 5. Data Cleaning and Preprocessing

**Objective:**  
Machine learning models cannot work with **missing data**. This exercise focuses on **data cleaning** and **handling missing values**.

Task 1   
Identifying Missing Data

- Using the command `isnull().sum()`, count the **number of missing values in each column** of the Titanic DataFrame.

- Which column has the **highest number of missing values**?

In [8]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [9]:
# Which column has the highest number of missing values
df.isnull().sum().sort_values(ascending=False).head(1)

Cabin    687
dtype: int64

In [10]:
df.isnull().sum().sort_values(ascending=False).index[0]

'Cabin'

Task 2   
Managing Missing Values – Removing Columns

- The `Cabin` column has too many missing values.  
  Using the `drop()` method, remove this column from `df` and store the result in a new DataFrame named `df_cleaned`.

In [11]:
df_cleaned = df.drop(columns=["Cabin"]).copy()
df_cleaned.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Embarked'],
      dtype='str')

Task 3     
Managing Missing Values – Replacement

- The `Age` column contains missing values. A common strategy is to replace them with the **median age** of the passengers.

- Using `fillna()`, fill the missing values in the `Age` column of `df_cleaned` with the **median age** you calculated.

- The `Embarked` column also has a few missing values. For **categorical data**, a good strategy is to replace missing values with the **mode (most frequent value)**. Find the mode of this column and use `fillna()` to replace the missing values.

- Run `isnull().sum()` again on `df_cleaned` to ensure there are **no remaining missing values** in the `Age` and `Embarked` columns.

In [12]:
df_cleaned.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Embarked         2
dtype: int64

In [13]:
MEDIAN_AGE_CLEAN = df_cleaned["Age"].median()
df_cleaned["Age"] = df_cleaned["Age"].fillna(MEDIAN_AGE_CLEAN)
df_cleaned.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(4)
memory usage: 76.7 KB

In [14]:
df_cleaned["Embarked"].mode()

0    S
Name: Embarked, dtype: str

In [15]:
df_cleaned["Embarked"].unique()
MOD_EMBARKED = df_cleaned["Embarked"].mode()[0]
df_cleaned["Embarked"] = df_cleaned["Embarked"].fillna(MOD_EMBARKED)
df_cleaned.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Embarked     891 non-null    str
dtypes: float64(2), int64(5), str(4)
memory usage: 76.7 KB

In [16]:
df_cleaned.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

Task 4   
Completing the Preprocessing Pipeline – Categorical Data

- The `Pclass` column represents a **categorical feature** (passenger class), but it is stored as an **integer**.

- Using the `astype()` method, convert the data type of the `Pclass` column in `df_cleaned` to a **categorical** type (or string).

In [28]:
df_cleaned["Pclass"] = df_cleaned["Pclass"].astype("category")
df_cleaned.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    category
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Embarked     891 non-null    str
dtypes: category(1), float64(2), int64(4), str(4)
memory usage: 70.6 KB

In [29]:
df_cleaned["Pclass"] = df_cleaned["Pclass"].astype(str)
df_cleaned.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    str
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Embarked     891 non-null    str
dtypes: float64(2), int64(4), str(5)
memory usage: 76.7 KB

### 6. Feature Engineering and Group Analysis

The quality of a machine learning model strongly depends on the quality of its features.  
This exercise teaches you how to transform existing features into **new and more informative features** to improve model performance.

In [30]:
df_cleaned.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C

Task 1   
Creating New Features from Existing Ones

- In `df_cleaned`, create a new column named `FamilySize`, defined as the sum of:
  - `SibSp` (number of brother, sister wife)
  - `Parch` (number of children )

In [32]:
df_cleaned["FamilySize"] = df_cleaned["SibSp"].add(df_cleaned["Parch"])
df_cleaned

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,FamilySize
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S,0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,S,3
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q,0