# Pandas

**pandas** is a powerful Python library for **working with tabular data and performing data analysis**.  
It provides data structures such as **DataFrame** and **Series**, similar to Excel tables or database tables, enabling fast and simple operations like reading, cleaning, filtering, aggregating, and analyzing data. It is widely used in data science, data analysis, and machine learning.

### Use Cases
- Reading and writing files (CSV, Excel, JSON, SQL)
- Data cleaning
- Filtering and selecting data
- Grouping and aggregating data (GroupBy)
- Merging and joining datasets
- Working with time series data
- Basic statistical analysis
- Preparing data for machine learning

In [2]:
import numpy as np
import pandas as pd
pd.__version__

'3.0.1'

In [3]:
pd?

Type:        module
String form: <module 'pandas' from 'c:\\Users\\hp\\AppData\\Local\\Programs\\Python\\Python314\\Lib\\site-packages\\pandas\\__init__.py'>
File:        c:\users\hp\appdata\local\programs\python\python314\lib\site-packages\pandas\__init__.py
Docstring:
pandas - a powerful data analysis and manipulation library for Python
=====================================================================

**pandas** is a Python package providing fast, flexible, and expressive data
structures designed to make working with "relational" or "labeled" data both
easy and intuitive. It aims to be the fundamental high-level building block for
doing practical, **real world** data analysis in Python. Additionally, it has
the broader goal of becoming **the most powerful and flexible open source data
analysis / manipulation tool available in any language**. It is already well on
its way toward this goal.

Main Features
-------------
Here are just a few of the things that pandas does well:

  - Easy handling of missing data in floating point as well as non-floating
    point data.
  - Size mutability: columns can be inserted and deleted from DataFrame and
    higher dimensional objects
  - Automatic and explicit data alignment: objects can be explicitly aligned
    to a set of labels, or the user can simply ignore the labels and let
    `Series`, `DataFrame`, etc. automatically align the data for you in
    computations.
  - Powerful, flexible group by functionality to perform split-apply-combine
    operations on data sets, for both aggregating and transforming data.
  - Make it easy to convert ragged, differently-indexed data in other Python
    and NumPy data structures into DataFrame objects.
  - Intelligent label-based slicing, fancy indexing, and subsetting of large
    data sets.
  - Intuitive merging and joining data sets.
  - Flexible reshaping and pivoting of data sets.
  - Hierarchical labeling of axes (possible to have multiple labels per tick).
  - Robust IO tools for loading data from flat files (CSV and delimited),
    Excel files, databases, and saving/loading data from the ultrafast HDF5
    format.
  - Time series-specific functionality: date range generation and frequency
    conversion, moving window statistics, date shifting and lagging.

### Series

python -> list   
numpy -> array   
pandas -> Series

Series has Value and Index toghether

In [6]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [ ]:
data.values # this is one attribute so has NOT ()

array([0.25, 0.5 , 0.75, 1.  ])

In [11]:
data.index # this is one attribute so has NOT ()
# stat index, end index, step of index

RangeIndex(start=0, stop=4, step=1)

In [14]:
data[1]

np.float64(0.5)

In [16]:
data[1:3] # [1, 3)

1    0.50
2    0.75
dtype: float64

In [19]:
# change index to my index
data =pd.Series([0.25, 0.5, 0.75, 1.0],
                index = ["a", "b", "c", "d"])

data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [21]:
data["b"] # change index and b is index

np.float64(0.5)

In [23]:
data =pd.Series([0.25, 0.5, 0.75, 1.0],
                index = [1, 12, 8, 2])
# index can be random form of number
data

1     0.25
12    0.50
8     0.75
2     1.00
dtype: float64

In [25]:
data[12]

np.float64(0.5)

In [27]:
# Series is same Dict in python
population_dict = {"California": 3832521,
                   "Texas": 26448193,
                   "Felorida": 19552860,
                   "Illinois": 12882135}
population_dict

{'California': 3832521,
 'Texas': 26448193,
 'Felorida': 19552860,
 'Illinois': 12882135}

In [28]:
population = pd.Series(population_dict)
population

California     3832521
Texas         26448193
Felorida      19552860
Illinois      12882135
dtype: int64

In [4]:
pd.Series(5, index = [100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [7]:
pd.Series({2:"a", 1:"b", 3:"c"}, index=[3,2]) # select index and sort

3    c
2    a
dtype: str

### DataFrame

In [11]:
population_dict = {"California": 3832521,
                   "Texas": 26448193,
                   "Felorida": 19552860,
                   "Illinois": 12882135}
population = pd.Series(population_dict)
pd.DataFrame(population)

                   0
California   3832521
Texas       26448193
Felorida    19552860
Illinois    12882135

In [20]:
pd.DataFrame({"population": population.index, "area": population})

            population      area
California  California   3832521
Texas            Texas  26448193
Felorida      Felorida  19552860
Illinois      Illinois  12882135