# Pandas

**pandas** is a powerful Python library for **working with tabular data and performing data analysis**.  
It provides data structures such as **DataFrame** and **Series**, similar to Excel tables or database tables, enabling fast and simple operations like reading, cleaning, filtering, aggregating, and analyzing data. It is widely used in data science, data analysis, and machine learning.

### Use Cases
- Reading and writing files (CSV, Excel, JSON, SQL)
- Data cleaning
- Filtering and selecting data
- Grouping and aggregating data (GroupBy)
- Merging and joining datasets
- Working with time series data
- Basic statistical analysis
- Preparing data for machine learning

In [1]:
import numpy as np
import pandas as pd
pd.__version__

'3.0.1'

In [3]:
pd?

Type:        module
String form: <module 'pandas' from 'c:\\Users\\hp\\AppData\\Local\\Programs\\Python\\Python314\\Lib\\site-packages\\pandas\\__init__.py'>
File:        c:\users\hp\appdata\local\programs\python\python314\lib\site-packages\pandas\__init__.py
Docstring:
pandas - a powerful data analysis and manipulation library for Python
=====================================================================

**pandas** is a Python package providing fast, flexible, and expressive data
structures designed to make working with "relational" or "labeled" data both
easy and intuitive. It aims to be the fundamental high-level building block for
doing practical, **real world** data analysis in Python. Additionally, it has
the broader goal of becoming **the most powerful and flexible open source data
analysis / manipulation tool available in any language**. It is already well on
its way toward this goal.

Main Features
-------------
Here are just a few of the things that pandas does well:

  - Easy handling of missing data in floating point as well as non-floating
    point data.
  - Size mutability: columns can be inserted and deleted from DataFrame and
    higher dimensional objects
  - Automatic and explicit data alignment: objects can be explicitly aligned
    to a set of labels, or the user can simply ignore the labels and let
    `Series`, `DataFrame`, etc. automatically align the data for you in
    computations.
  - Powerful, flexible group by functionality to perform split-apply-combine
    operations on data sets, for both aggregating and transforming data.
  - Make it easy to convert ragged, differently-indexed data in other Python
    and NumPy data structures into DataFrame objects.
  - Intelligent label-based slicing, fancy indexing, and subsetting of large
    data sets.
  - Intuitive merging and joining data sets.
  - Flexible reshaping and pivoting of data sets.
  - Hierarchical labeling of axes (possible to have multiple labels per tick).
  - Robust IO tools for loading data from flat files (CSV and delimited),
    Excel files, databases, and saving/loading data from the ultrafast HDF5
    format.
  - Time series-specific functionality: date range generation and frequency
    conversion, moving window statistics, date shifting and lagging.

### Series

python -> list   
numpy -> array   
pandas -> Series

Series has Value and Index toghether

In [6]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [ ]:
data.values # this is one attribute so has NOT ()

array([0.25, 0.5 , 0.75, 1.  ])

In [11]:
data.index # this is one attribute so has NOT ()
# stat index, end index, step of index

RangeIndex(start=0, stop=4, step=1)

In [14]:
data[1]

np.float64(0.5)

In [16]:
data[1:3] # [1, 3)

1    0.50
2    0.75
dtype: float64

In [19]:
# change index to my index
data =pd.Series([0.25, 0.5, 0.75, 1.0],
                index = ["a", "b", "c", "d"])

data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [21]:
data["b"] # change index and b is index

np.float64(0.5)

In [23]:
data =pd.Series([0.25, 0.5, 0.75, 1.0],
                index = [1, 12, 8, 2])
# index can be random form of number
data

1     0.25
12    0.50
8     0.75
2     1.00
dtype: float64

In [25]:
data[12]

np.float64(0.5)

In [27]:
# Series is same Dict in python
population_dict = {"California": 3832521,
                   "Texas": 26448193,
                   "Felorida": 19552860,
                   "Illinois": 12882135}
population_dict

{'California': 3832521,
 'Texas': 26448193,
 'Felorida': 19552860,
 'Illinois': 12882135}

In [28]:
population = pd.Series(population_dict)
population

California     3832521
Texas         26448193
Felorida      19552860
Illinois      12882135
dtype: int64

In [4]:
pd.Series(5, index = [100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [7]:
pd.Series({2:"a", 1:"b", 3:"c"}, index=[3,2]) # select index and sort

3    c
2    a
dtype: str

### DataFrame

In [11]:
population_dict = {"California": 3832521,
                   "Texas": 26448193,
                   "Felorida": 19552860,
                   "Illinois": 12882135}
population = pd.Series(population_dict)
pd.DataFrame(population)

                   0
California   3832521
Texas       26448193
Felorida    19552860
Illinois    12882135

In [21]:
states = pd.DataFrame({"population": population.index, "area": population})
states

            population      area
California  California   3832521
Texas            Texas  26448193
Felorida      Felorida  19552860
Illinois      Illinois  12882135

In [ ]:
states.index # this is an attrebute

Index(['California', 'Texas', 'Felorida', 'Illinois'], dtype='str')

In [24]:
states.columns # this is an attrebute

Index(['population', 'area'], dtype='str')

In [25]:
states["area"]

California     3832521
Texas         26448193
Felorida      19552860
Illinois      12882135
Name: area, dtype: int64

In [27]:
pd.DataFrame(population, columns=["population"])

            population
California     3832521
Texas         26448193
Felorida      19552860
Illinois      12882135

In [29]:
data = [{"a":i, "b": 2*i} for i in range(3)]
data

[{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'b': 4}]

In [32]:
df = pd.DataFrame(data)
df

   a  b
0  0  0
1  1  2
2  2  4

In [38]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Index([2, 3, 5, 7, 11], dtype='int64')

In [40]:
ind[1]

np.int64(3)

### Index and selection

In [42]:
data = pd.Series([0.25, 0.5, 0.75, 1], index=["a", "b", "c", "d"])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [43]:
data["b"]

np.float64(0.5)

In [44]:
"a" in data

True

In [49]:
data.keys() # this is a method and has ()

Index(['a', 'b', 'c', 'd'], dtype='str')

In [51]:
list(data.items()) # this is a method and has ()

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [53]:
data["e"] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [56]:
data["a":"c"] # explicir selection: index is string [a  c]

a    0.25
b    0.50
c    0.75
dtype: float64

In [58]:
data[0:2] # inplicit selection: select by number [0  2)

a    0.25
b    0.50
dtype: float64

In [61]:
data[["a", "e"]] # fancy indexing

a    0.25
e    1.25
dtype: float64

In [65]:
data = pd.Series(["a", "b", "c"], index = [1, 2, 5])
data

1    a
2    b
5    c
dtype: str

In [69]:
# local index(my index), pandas index(start from 0 to end by step 1)
data.loc[1], data.iloc[1]

('a', 'b')

### Oparating on data in pandas

In [4]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int32

In [6]:
df = pd.DataFrame(rng.randint(0, 10, (3,4)),
                  columns=["A", "B", "C", "D"])
df

   A  B  C  D
0  7  4  3  7
1  7  2  5  4
2  1  7  5  1

In [ ]:
np.exp(ser) # use numpy in pandas

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [8]:
np.sin(df *np.pi /4)

          A             B         C             D
0 -0.707107  1.224647e-16  0.707107 -7.071068e-01
1 -0.707107  1.000000e+00 -0.707107  1.224647e-16
2  0.707107 -7.071068e-01 -0.707107  7.071068e-01

In [ ]:
area = pd.Series({"Alaska": 1723337, "Texas": 695662,"Calofornia": 42397}, name="area")
population = pd.Series({"Calofornia": 38332521, "Texas": 26448193,"New York": 19651127}, name= "population")

In [20]:
population / area

Alaska               NaN
Calofornia    904.132863
New York             NaN
Texas          38.018740
dtype: float64

In [21]:
population + area

Alaska               NaN
Calofornia    38374918.0
New York             NaN
Texas         27143855.0
dtype: float64

In [23]:
population.add(area, fill_value=0)

Alaska         1723337.0
Calofornia    38374918.0
New York      19651127.0
Texas         27143855.0
dtype: float64

### Missing Data

In [ ]:
vals2 = np.array([1, "nan", 3, 4])
vals2.dtype # type nan change all type to str

dtype('<U21')

In [30]:
vals2 = np.array([1, np.nan, 3, 4])
vals2.dtype # nan by numpy is type of folat

dtype('float64')

nan safe function

In [32]:
np.sum(vals2), np.min(vals2), np.max(vals2)

(np.float64(nan), np.float64(nan), np.float64(nan))

In [33]:
np.nansum(vals2), np.nanmin(vals2), np.nanmax(vals2)

(np.float64(8.0), np.float64(1.0), np.float64(4.0))

In [39]:
vals2 = pd.Series([1, np.nan, 3, None]) # all nan is float in pandas
vals2

0    1.0
1    NaN
2    3.0
3    NaN
dtype: float64

In [ ]:
vals2.isnull().isnull(), vals2.notnull()

(0    False
 1     True
 2    False
 3     True
 dtype: bool,
 0     True
 1    False
 2     True
 3    False
 dtype: bool)

In [42]:
vals2.fillna(0), vals2.dropna()

(0    1.0
 1    0.0
 2    3.0
 3    0.0
 dtype: float64,
 0    1.0
 2    3.0
 dtype: float64)

In [50]:
df = pd.DataFrame(rng.randint(0, 10, (5,4)),
                  columns=["A", "B", "C", "D"])
df.iloc[1:4, 1:3] = None
df

   A    B    C  D
0  0  3.0  3.0  4
1  6  NaN  NaN  6
2  2  NaN  NaN  9
3  8  NaN  NaN  3
4  9  6.0  8.0  6

In [61]:
df["B"] = df["B"].bfill()
df

   A    B    C  D
0  0  3.0  3.0  4
1  6  6.0  NaN  6
2  2  6.0  NaN  9
3  8  6.0  NaN  3
4  9  6.0  8.0  6

In [63]:
df["C"] = df["C"].ffill()
df

   A    B    C  D
0  0  3.0  3.0  4
1  6  6.0  3.0  6
2  2  6.0  3.0  9
3  8  6.0  3.0  3
4  9  6.0  8.0  6